app = "car-dashboard-alerts" # Remplace par le nom de ton application Fly.io

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "python app.py" # Commande de démarrage si nécessaire

[[services]]
  http_checks = []
  internal_port = 8000
  protocol = "tcp"
  script = ""
  [services.concurrency]
    soft_limit = 25
    hard_limit = 50
  [services.ports]
    handlers = ["http"]
    port = 80
